@startuml chatapp
 hide circle
 skinparam linetype ortho

 entity "User (u)" as u {
     * <<PK>> uid : string : ユーザID
     --
     * uname       : string    : ユーザ名
     * email       : string    : メールアドレス
     displayName       : string    : ユーザ表示名
     avatarUrl       : string    : アバターURL
     created_at      : date      : 作成日時
     updated_at      : date      : 更新日時
 }
 
 entity "WorkSpace (ws)" as ws {
     * <<PK>> wsid : string : ワークスペースID
     --
     * wsname       : string    : ワークスペース名
     created_at                  : date      : 作成日時
     updated_at                  : date      : 更新日時
 }

entity "Channel (c)" as c {
     * <<PK>> cid : string : チャネルID
     --
     * <<FK>> wsid : string : ワークスペースID
     * cname       : string    : チャネル名
     created_at                  : date      : 作成日時
     updated_at                  : date      : 更新日時
 }

entity "Message (m)" as m {
     * <<PK>> mid : string : メッセージID
     --
     * <<FK>> cid : string : チャネルID
     * <<FK>> speaker       : string    : 発言者
     * message       : string    : メッセージ
     * sendtime       : date    : 送信時間
     created_at                  : date      : 作成日時
     updated_at                  : date      : 更新日時
 }

entity "Thread (t)" as t {
     * <<PK>> tid : string : スレッドID
     --
     * <<FK>> mid : string : メッセージID
     * <<FK>> speaker       : string    : 発言者
     * tmessage       : string    : スレッドメッセージ
     * sendtime       : string    : 送信時間
     created_at                  : date      : 作成日時
     updated_at                  : date      : 更新日時
 }

entity "RelationshipWCU (rwcu)" as rwcu {
     * <<FK>> wsid : string : ワークスペースID
     * <<FK>> cid : string : チャネルID
     * <<FK>> uid : string : ユーザID
     created_at                  : date      : 作成日時
     updated_at                  : date      : 更新日時
 }

 ws ||..{ c
 c ||..o{ m
 m ||..o{ t
 ws ||..o{ rwcu
 c ||..o{ rwcu
 u ||..o{ rwcu
 

 @enduml