@startuml sushi
 hide circle
 skinparam linetype ortho
 
 entity "商品マスタ (Product)" as Product {
     * <<PK>> p_id : int : 商品ID
     --
     * <<FK>> pt_id              : int : 商品種類ID
     * <<FK>> price_id           : int : 値段ID
     * p_name                    : string    : 商品名
     created_at                  : date      : 作成日時
     updated_at                  : date      : 更新日時
 }

 entity "商品種類 (ProductType)" as ProductType {
     * <<PK>> pt_id : int : 商品種類ID
     --
     * pt_name                    : string    : 商品種類名
     created_at                  : date      : 作成日時
     updated_at                  : date      : 更新日時
 }

  entity "値段 (Price)" as Price {
     * <<PK>> price_id              : int : 値段ID
     --
     * price                    : int    : 値段
     created_at                  : date      : 作成日時
     updated_at                  : date      : 更新日時
 }

 entity "顧客 (Customer)" as Customer {
     * <<PK>> c_id : int : 顧客ID
     --
     * c_name    : string    : 名前
     * phonenumber  : string    : 電話番号
     created_at      : date      : 作成日時
     updated_at      : date      : 更新日時
 }

 entity "注文詳細 (OrderDetails)" as OrderDetails {
     * <<FK>> od_id : int : 注文ID
     * <<FK>> c_id          : int : 顧客ID
     * <<FK>> p_id          : int : 商品ID
     * amount: int : 注文数量 
     * sabi_flag: int : サビフラグ(0:あり, 1:なし)
     * ricesize_flag: int : しゃりフラグ(0:通常, 1:大, 2:小)
     * ricekind_flag: int : しゃり種類フラグ(0:すし酢, 1:赤酢)
     created_at : date : 作成日時
     updated_at : date : 更新日時
 }

entity "注文 (Order)" as Order {
     * <<FK>> od_id              : int : 注文ID
     --
     * <<FK>> c_id          : int : 顧客ID
     * isPayment  : boolean    : 支払いフラグ
     * totalAmount: int : 合計金額
     * order_date                : date      : 注文日時
     created_at                  : date      : 作成日時
     updated_at                  : date      : 更新日時
 }

 ProductType ||..{ Product
 Price ||..{ Product
 Customer ||..o{ OrderDetails
 Price ||..o{ OrderDetails
 OrderDetails }..|| Order
 Customer ||..{ Order 

 @enduml